from .path import (
    CCIMAR11_DIR,
    CCIMAR11_PATH,
    ACOES_ORCAMENTARIAS_SQL_PATH,
    TEMPLATE_TEST1_PATH,
    TEMPLATE_TEST2_PATH,
    TEMPLATE_TEST3_PATH,
    TEMPLATE_RELATORIO_PATH,
    OBJETIVOS_NAVAIS_PATH,
    OM_REPRESENTATIVAS_PATH,
    CONFIG_PAINT_PATH,
    CADASTRO_OBJETOS_AUDITAVEIS_PATH
    )